name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE: devopsprojectcr.azurecr.io/frontend
      BACKEND_IMAGE: devopsprojectcr.azurecr.io/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE ./front/presentation_layer
          docker push $FRONTEND_IMAGE

      - name: Build and Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE ./back/application_layer
          docker push $BACKEND_IMAGE

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: devops-frontend-app
          images: ${{ env.FRONTEND_IMAGE }}

      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: devops-backend-app
          images: ${{ env.BACKEND_IMAGE }}
